favicon = "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/PjxzdmcgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgNjQgNjQiIGhlaWdodD0iNjRweCIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIwIDAgNjQgNjQiIHdpZHRoPSI2NHB4IiB4bWw6c3BhY2U9InByZXNlcnZlIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj48ZyBpZD0iTGF5ZXJfMSI+PGc+PGNpcmNsZSBjeD0iMzIiIGN5PSIzMiIgZmlsbD0iI0M3NUM1QyIgcj0iMzIiLz48L2c+PGcgb3BhY2l0eT0iMC4yIj48Zz48cGF0aCBkPSJNNDkuOTgyLDMxLjAwM2MtMC4wOTQtNS41MjItNC41NzQtMTAuNDQyLTEwLjEwNy0xMC40NDJjLTMuMiwwLTYuMDE5LDEuNjc0LTcuODc1LDQuMTMxICAgICBjLTEuODU2LTIuNDU3LTQuNjc2LTQuMTMxLTcuODc1LTQuMTMxYy01LjUzMywwLTEwLjAxMiw0LjkyMS0xMC4xMDcsMTAuNDQySDE0YzAsMC4wMzQsMC4wMDcsMC4wNjUsMC4wMDcsMC4wOTkgICAgIGMwLDAuMDI1LTAuMDA3LDAuMDQ5LTAuMDA3LDAuMDc2YzAsMC4xNTUsMC4wMzgsMC4yNzIsMC4wNDUsMC40MjFjMC40OTUsMTQuMDcxLDE3LjgxMywxOS44NCwxNy44MTMsMTkuODQgICAgIHMxNy41NzItNS43NjIsMTguMDkyLTE5LjgxOEM0OS45NTksMzEuNDY0LDUwLDMxLjM0LDUwLDMxLjE3OGMwLTAuMDI3LTAuMDA3LTAuMDUyLTAuMDA3LTAuMDc2YzAtMC4wMzYsMC4wMDctMC4wNjUsMC4wMDctMC4wOTkgICAgIEg0OS45ODJ6IiBmaWxsPSIjMjMxRjIwIi8+PC9nPjwvZz48Zz48Zz48cGF0aCBkPSJNNDkuOTgyLDI5LjAwM2MtMC4wOTQtNS41MjItNC41NzQtMTAuNDQyLTEwLjEwNy0xMC40NDJjLTMuMiwwLTYuMDE5LDEuNjc0LTcuODc1LDQuMTMxICAgICBjLTEuODU2LTIuNDU3LTQuNjc2LTQuMTMxLTcuODc1LTQuMTMxYy01LjUzMywwLTEwLjAxMiw0LjkyMS0xMC4xMDcsMTAuNDQySDE0YzAsMC4wMzQsMC4wMDcsMC4wNjUsMC4wMDcsMC4wOTkgICAgIGMwLDAuMDI1LTAuMDA3LDAuMDQ5LTAuMDA3LDAuMDc2YzAsMC4xNTUsMC4wMzgsMC4yNzIsMC4wNDUsMC40MjFjMC40OTUsMTQuMDcxLDE3LjgxMywxOS44NCwxNy44MTMsMTkuODQgICAgIHMxNy41NzItNS43NjIsMTguMDkyLTE5LjgxOEM0OS45NTksMjkuNDY0LDUwLDI5LjM0LDUwLDI5LjE3OGMwLTAuMDI3LTAuMDA3LTAuMDUyLTAuMDA3LTAuMDc2YzAtMC4wMzYsMC4wMDctMC4wNjUsMC4wMDctMC4wOTkgICAgIEg0OS45ODJ6IiBmaWxsPSIjRkZGRkZGIi8+PC9nPjwvZz48L2c+PGcgaWQ9IkxheWVyXzIiLz48L3N2Zz4="
refresh = 10
title = "My Health Monitor"

[[checks]]
service = "Lua Service"
description = "Random number is even"
lua = """
math.randomseed( os.time() )
num = math.random(1, 2)
if num % 2 == 0 then
    setHealthy()
else
    setSick()
end  
"""

[[checks]]
service = "Lua Service"
description = "Random number is odd"
lua = """
math.randomseed( os.time() )
num = math.random(1, 2)
if num % 2 ~= 0 then
    setHealthy()
else
    setSick()
end  
"""

[[checks]]
service = "Lua Service"
description = "Always healthy"
lua = "setHealthy()"

[[checks]]
service = "HTTP Checker"
description = "HTTP status check"
lua = """
local http = require("http")
response, error_message = http.request("GET", "http://example.com")
if response.status_code == 200 then
    setHealthy()
else
    setSick()
end
"""

[[checks]]
service = "Module Loading"
description = "Load a module"
lua = """
local greetings = require("greetings")
greetings.sayHello()
"""

[[modules]]
name = "greetings"
lua = """
local M = {}

local function sayMyName()
  print('Hrunkner')
end

function M.sayHello()
  print('Why hello there')
  sayMyName()
end

return M
"""
